// packages/tsugite/components/Card/Card.vue
<!-- Card — the Vue renderer of lib/card.ts. Same recipe, same markup; Vue idioms only
     where the host framework differs (a slot, v-bind for the attributes). -->
<script setup lang="ts">
import { useSlots } from "vue";
import "./Card.css";
import { resolveCard } from "../../lib/card";

const props = defineProps<{
  element?: string;
  padding?: string;
  border?: boolean;
  elevation?: string;
  class?: string;
}>();
defineOptions({ inheritAttrs: false });

const slots = useSlots();
const card = resolveCard({
  element: props.element,
  padding: props.padding,
  border: props.border,
  elevation: props.elevation,
  class: props.class,
  hasContent: !!slots.default,
});
</script>

<template>
  <component v-if="card.mode === 'render'" :is="card.tag" :class="card.className" v-bind="{ ...card.attrs, ...$attrs }">
    <slot />
  </component>
  <div v-else-if="card.mode === 'error'" style="color: red; border: 2px solid red; padding: 0.5rem">
    &times; Card: {{ card.errorMessage }}
  </div>
</template>

// packages/tsugite/components/Card/Card.tsx
// Card — the React renderer of lib/card.ts. Same recipe, same markup; React idioms
// only where the host framework differs (children instead of a slot).
import type { ReactNode } from "react";
import { createElement } from "react";
import "./Card.css";
import { resolveCard } from "../../lib/card";

export interface CardProps {
  element?: string;
  padding?: string;
  border?: boolean;
  elevation?: string;
  className?: string;
  children?: ReactNode;
  [key: string]: unknown;
}

export default function Card({ element, padding, border, elevation, className, children, ...rest }: CardProps) {
  const card = resolveCard({
    element,
    padding,
    border,
    elevation,
    class: className,
    hasContent: children != null && children !== false && children !== "",
  });

  if (card.mode === "suppress") return null;
  if (card.mode === "error") {
    // Mirrors DevError: visible in development, silent in production.
    if (process.env.NODE_ENV === "production") return null;
    return createElement(
      "div",
      { style: { color: "red", border: "2px solid red", padding: "0.5rem" } },
      `\u00d7 Card: ${card.errorMessage}`,
    );
  }

  return createElement(card.tag, { className: card.className, ...card.attrs, ...rest }, children);
}
